server.port=8082
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl19c
spring.datasource.username=ecomuser
spring.datasource.password=ecom
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.com.mycomp=DEBUG

logging.file.name=C:\\IntelliJWS\\EcomMicroAppFeb26\\orders\\logs\\orders.log
#logging.file.path=
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
#rolling policy for log files
#logging.file.max-size=1KB
#logging.file.max-history=30
#logging.file.total-size-cap=10MB

eureka.instance.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.security.user.name=ecomuser
spring.security.user.password=ecompassword

ecom.jwt.secret=myKey123ghtkjkjsdfkjnfnkjdgndkjfghkdjngfnfgfdg
